### ISSUE TITLE
il coso non cosa

### ISSUE THREAD

**Issue by jucasoft** [acareccia/MariangiongiangelaBot#1]
ciao coso, mi sembra che il coso non cosa.

**Comment by acareccia** [comment]
cosa cosi cosa nel coso?

**Comment by jucasoft** [comment]
ho povato il coso sul bianco, poi ho provato sul coso rosso, ma stampava bene.
come stai coso?

**Comment by jucasoft** [comment]
lo hai cosato sul coso bianco?

**Comment by acareccia** [comment]
Ho ricosato il coso su Telecoso
